version: '1.0'

# This file is an example to build all this images.
# run: docker-compose build

services:
  app-latest:
    build: docker/images/php-apache/base
    image: matheusbiagini/docker-lamp:latest

  app-base:
    build: docker/images/php-apache/base
    image: matheusbiagini/docker-lamp:base

  app-dev:
    build: docker/images/php-apache/dev
    image: matheusbiagini/docker-lamp:dev
